### ISSUE TITLE
Add a copy button to copy the generated url

### ISSUE THREAD

**Issue by Bikram-ghuku** [Swarnendu0123/http-request-inspector#2]
![image](https://github.com/Swarnendu0123/request-alalyser/assets/37508038/9a3402c0-fb2b-40f4-949a-28fbb9b5029b)

- Add a button at the end of the endpoint url bar to copy the url

**Comment by swrno** [comment]
You can add the add to clipboard button, here is the preline UI that you can use [Preline](https://preline.co/docs/clipboard.html)
