### ISSUE TITLE
Fix installation.md file

### ISSUE THREAD

**Issue by krishna-singha** [Swarnendu0123/http-request-inspector#6]
Addressing issues in the installation.md file to enhance clarity and completeness.

There are something still left: 

1. Write the steps to setup `config.js` in client:
      Change the BACKEND_URL='http://localhost:8000'.
2. Write steps to setup `config.js` in server:
      Change the BACKEND_URL='http://localhost:8000'.
       And the FRONTEND_URL='http://localhost:5173'.
3. Write the step to comment 
```
app.use("/v1", (req, res, next) => {
    if (req.rawHeaders.includes(FRONTEND_URL)) {
        next();
    } else {
        res.json({ error: "Invalid URL" })
    }
});
```
the middleware from the `server/index.js` file. Because it is only for validation of the frontend. During development, we don't really need this.

**Comment by swrno** [comment]
There are something still left: 

1. Write the steps to setup `config.js` in both `client` and `server`. 
2. Write the step to comment 
```
app.use("/v1", (req, res, next) => {
    if (req.rawHeaders.includes(FRONTEND_URL)) {
        next();
    } else {
        res.json({ error: "Invalid URL" })
    }
});
```
the middleware from the `server/index.js` file. Because it is only for validation of the frontend.
